name: Python CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu Klonla
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Gereksinimleri Kur
        run: |
          pip install -r requirements.txt
          pip install coverage flake8

      - name: Kod Kalitesini Kontrol Et (flake8)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true

      - name: Testleri Çalıştır ve Kapsam Al
        run: |
          coverage run -m pytest
          coverage report
